name: chatverse_example
description: Example app for ChatVerse library.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chatverse:
    path: ../
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  provider: ^6.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
