name: chatverse
description: A comprehensive Flutter chat library with Firebase integration, featuring advanced UI, group chat support, and real-time messaging capabilities.
version: 0.0.1
homepage: https://github.com/yourusername/chatverse

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  provider: ^6.1.1
  uuid: ^4.2.2
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  flutter_chat_bubble: ^2.0.2
  timeago: ^3.6.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.2
  emoji_picker_flutter: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.3
  build_runner: ^2.4.7
  test: ^1.24.9
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
